server:
  port: 8080

#springboot程序使用10-13,springboot+shiro使用6-9
spring:
#  mvc:
#    view:
#      prefix: /
#      suffix: .html
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springbootmybatis.sbm.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true